// <auto-generated />
namespace Universe.Fias.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddFiasCsvFolderPath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFiasCsvFolderPath));
        
        string IMigrationMetadata.Id
        {
            get { return "202208171418500_AddFiasCsvFolderPath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
